name: Continuos Integration - Tests

on: [pull_request]

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using node.js
      uses: actions/setup-node@v2
      with: 
          node-version: 23.
    - name: run test
      run: |
        npm install
        npm run test